### ISSUE TITLE
github workflow failure

### ISSUE THREAD

**Issue by creaturenex** [shipyard/express-starter#5]
This github workflow fails because it is looking for a Github Env Variable.

![Screenshot(1)](https://github.com/shipyard/express-starter/assets/15052690/3c73cfd7-8b6f-403b-a26e-eede37d6b522)

I tried to add a fake token using github env secrets and env variables but it still failed, I know this is for testing purposes but it should only print the token variables. 
SHIPYARD_API_TOKEN

**Comment by nbeck415** [comment]
Hi @creaturenex, thanks for pointing this out. This happens on all sample repos. If you have a valid Shipyard token (not enabled on trial accounts) and a Shipyard application created from a fork of this repo, the workflow should run successfully, but we will make the output more verbose.

**Comment by creaturenex** [comment]
Closing at this is working as intended on the starter app with trial account.
